### ISSUE TITLE
Repeat at the same time will cause problems

### ISSUE THREAD

**Issue by quert999** [sudip-mondal-2002/drum-kit-app#1]
should use sound pool, set maxstreams, initialize and traverse all resources, load with soundpool.load, play with soundpool.play when click btns

**Comment by sudip-mondal-2002** [comment]
Hi there, thank you for opening this issue. I will look into it. Otherwise you can fork this repository, update your code and create a pull request.
Thanking you.

**Comment by sudip-mondal-2002** [comment]
Thank you for your contribution, I am closing this issue now.
